### PR TITLE
Added ability to customize sampling rate when loading new sound.

### PR DESCRIPTION
**Pull request by sirkrypt0**

### CODE REVIEW

**Comment by benrobby** [comment]
Hey, thanks for your contribution, looks good to me! While you're at it: do you mind disabling the failing test so we have a green pipeline? I would but I can't get squeak running on my mac :(

**Comment by ekrebs5** [comment]
> Hey, thanks for your contribution, looks good to me! While you're at it: do you mind disabling the failing test so we have a green pipeline? I would but I can't get squeak running on my mac :(

Let's not do that, I'll fix the baseline so Pheno is loaded correctly again

The PR looks good to me, I will test it later

**Comment by ekrebs5** [comment]
Looks good in general, two things:
- I fixed the failing test on our master (aka I changed the baseline and package structure), that needs to be merged into your master
- In addition to the feature there should be a test for this

**Comment by sidietz** [comment]
In the RFC of the OPUS Codec sampling rates are described as follows:
48kHz
96kHz
128kHz

For legacy reasons non Sony (R) High-Res frequencies (may be looked up by someone like @ekrebs5)

FYI:
[OPUS Codec](https://tools.ietf.org/html/rfc6716)

**Pull request merged**
